添加订单：
1. 电话号码录入改为发QQ
2. 快递公司选择下拉框增加 顺丰COD和宅急送COD
3. 增加LC号输入 （数据库订单表增加LC号字段) alicod varchar30
4. 增加发货状态：成功-未结算 退货-未结算 问题件（已加） 批发价为0
5. 盈利计算 & VIP盈利计算 VIP账户显示

360浏览器登录后白屏问题

20140320
增加黑名单功能：
/admin/template/user/index.html & add.html & edit.html
/admin/template/manage/index.html & edit.html
/admin/module/manageMod.class.php
/module/manageMod.class.php  &  accountsMod.class.php
/template/user_index.html(加VIP）

IP黑名单库：
